version: "3.7"

services:
  # Service mysql
  db:
    image: mysql:5.7
    container_name: mysql_rest 
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resta_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql-data:/var/lib/mysql:rw

  # Service lumen
  lumen:
    container_name: api_rest
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    build: .
    command: php -S lumen:8000 -t public
    restart: always
    depends_on:
      - db

  # Service Adminer
  adminer:
    image: adminer
    container_name: adminer_rest
    restart: always
    ports:
      - 8081:8080

volumes:
  schemas: {}

networks:
  redjalisco:
